site_name: Tutorial de acceso al HPC de la Facultad de Ingeniería UNAL
site_description: Guías de conexión al HPC desde Windows y Linux
docs_dir: docs
nav:
  - Inicio: index.md
  - Windows: guia-windows.md
  - Linux: guia-linux.md
theme:
  name: readthedocs
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
